### ISSUE TITLE
Creating release tags

### ISSUE THREAD

**Issue by jonringer** [linnik/roundrobin#3]
I noticed in https://github.com/NixOS/nixpkgs/pull/185087 that there's not corresponding release tag for 0.0.2.

Do you mind creating a tag moving forward? it helps downstream consumers to ensure that a particular commit was meant to be released and consumed by others.

**Comment by jonathanspw** [comment]
This would be helpful for Fedora packaging as well.

**Comment by linnik** [comment]
added release tags
